### ISSUE TITLE
Chrome extension gone?

### ISSUE THREAD

**Issue by Steffan153** [mitchas/Keyframes#15]
![image](https://user-images.githubusercontent.com/40404519/117514555-5ea4c300-af51-11eb-8f48-714f856db62a.png)

Gone from the Web Store too. Do you have a .crx file or something?

**Comment by mitchas** [comment]
Hey there, that extension was for the old version of Keyframes. It worked a lot differently, was unreliable, and was just generally poorly coded. I do have a replacement in progress, I just haven't had time to finish it up. Hopefully soon!

**Comment by LorenzWieseke** [comment]
Any update ?

**Comment by mitchas** [comment]
@LorenzWieseke Just got a new version of the website out - now I'm moving on to redoing the extension. Hopefully soon.
