### ISSUE TITLE
After adding a step, be able to move it. 

### ISSUE THREAD

**Issue by jonathan-s** [mitchas/Keyframes#7]
When you've added a step, it'd be great if you could move the step to a different percentage. Right now you need to delete the step and add a new step.

**Comment by asmirbelkic** [comment]
the extension is marked as malicious on edge

**Comment by mitchas** [comment]
Closing - new version of keyframes, feature almost ready.

**Comment by parallax4** [comment]
@mitchas Any update on this? This would be a really nice feature to have.

**Comment by TomorrowToday** [comment]
Please consider reopening this. Was very excited to find your tool, but without this feature it's no easier than editing keyframes in browser console inspect.
